CURRENT_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export ROOT_DIR=$CURRENT_SCRIPT_DIR/../..
export SCRIPTS_DIR=$ROOT_DIR/scripts

export DEPLOYMENT_SCRIPTS_DIR=$SCRIPTS_DIR/deploy
export PRE_DEPLOYMENT_SCRIPT=$DEPLOYMENT_SCRIPTS_DIR/pre_deployment.sh
export DEPLOYMENT_SCRIPT=$DEPLOYMENT_SCRIPTS_DIR/deploy.sh
export POST_DEPLOYMENT_SCRIPT=$DEPLOYMENT_SCRIPTS_DIR/post_deployment.sh

export SERVER_DIR=$ROOT_DIR/server
export SERVER_DEPLOYMENT_SCRIPT=$SERVER_DIR/deploy.sh
export SERVER_RVMRC=$SERVER_DIR/.rvmrc

export APP_DIR_NAME=app
export APP_DIR=$ROOT_DIR/$APP_DIR_NAME
export APP_DEPLOYMENT_SCRIPT=$APP_DIR/deploy.sh
export APP_WWW_DIR=$APP_DIR/assets/www
export APP_WWW_RVMRC=$APP_WWW_DIR/.rvmrc

export ACCEPTANCE_TEST_DIR=$ROOT_DIR/app_acceptance_test
export ACCEPTANCE_TEST_SCRIPT=$ACCEPTANCE_TEST_DIR/at.sh

# remote directory structure
export ROOT_DIR_APP_SERVER=/home/$APP_SERVER_USER_NAME
export DEPLOYMENT_DIR_NAME=auto_deployment
export DEPLOYMENT_DIR_APP_SERVER=$ROOT_DIR_APP_SERVER/$DEPLOYMENT_DIR_NAME
export APP_DIR_APP_SERVER=$DEPLOYMENT_DIR_APP_SERVER/releases/$APP_DIR_NAME
export APP_GEMFILE_APP_SERVER=$APP_DIR_APP_SERVER/assets/www/Gemfile
